# Generated by Django 4.2 on 2023-04-13 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AXEapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeEvaluacion',
            fields=[
                ('cod_evaluacion', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('nom_institucion', models.CharField(default=-1, max_length=40)),
                ('des_evaluacion', models.CharField(default=-1, max_length=20)),
            ],
            options={
                'db_table': 'axe_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Centro_Educativo',
            fields=[
                ('cod_identificador', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('cod_sace', models.IntegerField(default=-1, max_length=40)),
                ('nom_institucion', models.CharField(default=-1, max_length=20)),
                ('tip_categoria_institucion', models.CharField(default=-1, max_length=40)),
            ],
            options={
                'db_table': 'centro_educativo',
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('cod_donacion', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('nom_institucion', models.CharField(default=-1, max_length=40)),
                ('tip_donacion', models.CharField(default=-1, max_length=40)),
                ('des_donacion', models.CharField(default=-1, max_length=40)),
                ('fec_donacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donaciones',
            },
        ),
        migrations.CreateModel(
            name='Donantes',
            fields=[
                ('cod_donantes', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('cod_usuario', models.CharField(default=-1, max_length=20)),
                ('direccion', models.CharField(default=-1, max_length=50)),
                ('telefono', models.CharField(default=-1, max_length=20)),
                ('email', models.CharField(default=-1, max_length=50)),
                ('fec_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'donantes',
            },
        ),
        migrations.CreateModel(
            name='Recuperar_Contrasenia',
            fields=[
                ('cod_pregunta_respuesta', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('cod_usuario', models.IntegerField(default=-1, max_length=40)),
                ('nom_pregunta', models.CharField(default=-1, max_length=200)),
                ('des_respuesta', models.CharField(default=-1, max_length=200)),
            ],
            options={
                'db_table': 'recuperar_contrasenia',
            },
        ),
        migrations.CreateModel(
            name='Seg_Permisos',
            fields=[
                ('cod_permisos', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('per_insercion', models.CharField(default=-1, max_length=20)),
                ('per_eliminar', models.CharField(default=-1, max_length=20)),
                ('per_actualizar', models.CharField(default=-1, max_length=20)),
                ('per_consultar', models.CharField(default=-1, max_length=20)),
                ('fec_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_rol', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'seg_permisos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cod_usuario', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(default=-1, max_length=40)),
                ('contrasenia', models.CharField(default=-1, max_length=20)),
                ('estado_usuario', models.BooleanField(default=-1, max_length=20)),
                ('fec_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_rol', models.IntegerField(default=-1, max_length=20)),
                ('telefono', models.CharField(default=-1, max_length=15)),
                ('email', models.CharField(default=-1, max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
