# Generated by Django 4.2 on 2023-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AXEapp', '0002_axeevaluacion_centro_educativo_donaciones_donantes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recuperar_contrasenia',
            old_name='nom_pregunta',
            new_name='nomb_pregunta',
        ),
        migrations.AddField(
            model_name='donantes',
            name='identidad',
            field=models.CharField(default=-1, max_length=15),
        ),
        migrations.AddField(
            model_name='donantes',
            name='nombre',
            field=models.CharField(default=-1, max_length=100),
        ),
        migrations.AlterField(
            model_name='centro_educativo',
            name='cod_sace',
            field=models.CharField(default=-1, max_length=40),
        ),
    ]
